# Generated by Django 4.1.4 on 2023-01-27 10:55

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Answered'), (2, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
