# Generated by Django 4.1.4 on 2023-01-27 10:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_application_country_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
