# Generated by Django 4.1.4 on 2023-01-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_application_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Answered'), (2, 'Done')], default=0),
        ),
    ]
